// PET01 reproducible asset fetch: downloads the official Cubism SDK for Web
// (pinned URL + sha256) into .pet-sdk/ (gitignored — the zip contains Live2D
// proprietary assets that must not enter the repository), extracts it, and
// bundles the MIT-licensed Framework sources into a single IIFE we can serve
// to the verification harness. Sample models ship inside the official zip.
//
//   node scripts/fetch-pet-sdk.mjs
import { createHash } from 'node:crypto'
import { cp, mkdir } from 'node:fs/promises'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { createRequire } from 'node:module'
import { resolve, dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { get as httpGet } from 'node:http'
import { get as httpsGet } from 'node:https'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const target = join(root, '.pet-sdk')
const ZIP_URL = 'https://cubism.live2d.com/sdk-web/bin/CubismSdkForWeb-5-r.5.zip'
const ZIP_SHA256 = '67064a7fb1812cf502f5c4a03bfe12cc638c75a621bb4acf06bb28763df06ba0'
const sdkDir = join(target, 'CubismSdkForWeb-5-r.5')

const download = (url, to) =>
  new Promise((done, fail) => {
    const get = url.startsWith('http:') ? httpGet : httpsGet
    get(url, response => {
      if (response.statusCode !== 200) return fail(new Error(`GET ${url} -> ${response.statusCode}`))
      const chunks = []
      response.on('data', chunk => chunks.push(chunk))
      response.on('end', () => {
        writeFileSync(to, Buffer.concat(chunks))
        done()
      })
    }).on('error', fail)
  })

const sha256 = file => createHash('sha256').update(readFileSync(file)).digest('hex')

const zipPath = join(target, 'CubismSdkForWeb-5-r.5.zip')
if (!existsSync(zipPath) || sha256(zipPath) !== ZIP_SHA256) {
  console.log(`downloading ${ZIP_URL}`)
  await download(ZIP_URL, zipPath)
}
const actual = sha256(zipPath)
if (actual !== ZIP_SHA256) throw new Error(`sha256 mismatch: ${actual}`)
console.log(`zip ok (sha256 ${actual.slice(0, 16)}…)`)

if (!existsSync(sdkDir)) {
  execFileSync('tar', ['-xf', zipPath, '-C', target], { stdio: 'inherit' })
}
for (const mustExist of [
  'Core/live2dcubismcore.min.js',
  'Core/live2dcubismcore.d.ts',
  'Framework/src/live2dcubismframework.ts',
  'Framework/Shaders/WebGL',
  'Samples/Resources/Haru/Haru.model3.json',
  'Samples/Resources/Haru/motions/haru_g_idle.motion3.json',
]) {
  if (!existsSync(join(sdkDir, mustExist))) throw new Error(`SDK incomplete: missing ${mustExist}`)
}
console.log('SDK extracted and verified')

// Umbrella entry exposing the subset the harness drives; keep in sync with
// tests/desktop/pet/verify.js.
const entry = join(target, 'framework-entry.ts')
writeFileSync(entry, `// Generated by scripts/fetch-pet-sdk.mjs
export { CubismFramework } from './CubismSdkForWeb-5-r.5/Framework/src/live2dcubismframework'
export { CubismMatrix44 } from './CubismSdkForWeb-5-r.5/Framework/src/math/cubismmatrix44'
export { CubismModel } from './CubismSdkForWeb-5-r.5/Framework/src/model/cubismmodel'
export { CubismMoc } from './CubismSdkForWeb-5-r.5/Framework/src/model/cubismmoc'
export { CubismRenderer_WebGL } from './CubismSdkForWeb-5-r.5/Framework/src/rendering/cubismrenderer_webgl'
export { CubismMotion } from './CubismSdkForWeb-5-r.5/Framework/src/motion/cubismmotion'
export { CubismMotionManager } from './CubismSdkForWeb-5-r.5/Framework/src/motion/cubismmotionmanager'
export { CubismMotionQueueManager } from './CubismSdkForWeb-5-r.5/Framework/src/motion/cubismmotionqueuemanager'
export { CubismPhysics } from './CubismSdkForWeb-5-r.5/Framework/src/physics/cubismphysics'
export { CubismModelSettingJson } from './CubismSdkForWeb-5-r.5/Framework/src/cubismmodelsettingjson'
export { CubismJson } from './CubismSdkForWeb-5-r.5/Framework/src/utils/cubismjson'
export { CubismIdManager } from './CubismSdkForWeb-5-r.5/Framework/src/id/cubismidmanager'
`)

const require = createRequire(join(root, 'package.json'))
const esbuild = require('esbuild')
await esbuild.build({
  entryPoints: [entry],
  bundle: true,
  minify: true,
  format: 'iife',
  globalName: 'Live2DCubismFramework',
  outfile: join(target, 'dist/live2dcubismframework.min.js'),
})
const publicLive2d = join(root, 'apps/desktop/src/renderer/public/live2d')
await mkdir(publicLive2d, { recursive: true })
await cp(join(sdkDir, 'Core/live2dcubismcore.min.js'), join(publicLive2d, 'live2dcubismcore.min.js'))
await cp(join(target, 'dist/live2dcubismframework.min.js'), join(publicLive2d, 'live2dcubismframework.min.js'))
await cp(join(sdkDir, 'Core/LICENSE.md'), join(publicLive2d, 'CORE-LICENSE.md'))
await cp(join(sdkDir, 'Core/RedistributableFiles.txt'), join(publicLive2d, 'RedistributableFiles.txt'))
await cp(join(sdkDir, 'Framework/LICENSE.md'), join(publicLive2d, 'FRAMEWORK-LICENSE.md'))
await cp(join(sdkDir, 'Framework/Shaders/WebGL'), join(publicLive2d, 'shaders'), { recursive: true })
console.log('runtime staged into apps/desktop/src/renderer/public/live2d (gitignored, local only)')
console.log('next: pnpm exec playwright test tests/desktop/pet-verify.spec.ts')
